// automatically generated by the FlatBuffers compiler, do not modify

package argo;

public final class SecIdSource {
  private SecIdSource() { }
  public static final byte RIC = 0;
  public static final byte SEDOL = 1;
  public static final byte TICKER = 2;

  private static final String[] names = { "RIC", "SEDOL", "TICKER", };

  public static String name(int e) { return names[e]; }
};

