// automatically generated by the FlatBuffers compiler, do not modify

package argo;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Security extends Table {
  public static Security getRootAsSecurity(ByteBuffer _bb) { return getRootAsSecurity(_bb, new Security()); }
  public static Security getRootAsSecurity(ByteBuffer _bb, Security obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Security __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String ric() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ricAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String ticker() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tickerAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createSecurity(FlatBufferBuilder builder,
      long id,
      int ricOffset,
      int tickerOffset) {
    builder.startObject(3);
    Security.addId(builder, id);
    Security.addTicker(builder, tickerOffset);
    Security.addRic(builder, ricOffset);
    return Security.endSecurity(builder);
  }

  public static void startSecurity(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0); }
  public static void addRic(FlatBufferBuilder builder, int ricOffset) { builder.addOffset(1, ricOffset, 0); }
  public static void addTicker(FlatBufferBuilder builder, int tickerOffset) { builder.addOffset(2, tickerOffset, 0); }
  public static int endSecurity(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

