// automatically generated by the FlatBuffers compiler, do not modify

package argo;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Thing extends Table {
  public static Thing getRootAsThing(ByteBuffer _bb) { return getRootAsThing(_bb, new Thing()); }
  public static Thing getRootAsThing(ByteBuffer _bb, Thing obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Thing __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createThing(FlatBufferBuilder builder,
      int nameOffset) {
    builder.startObject(1);
    Thing.addName(builder, nameOffset);
    return Thing.endThing(builder);
  }

  public static void startThing(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static int endThing(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

