# automatically generated by the FlatBuffers compiler, do not modify

# namespace: argo

import flatbuffers

class SecurityList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSecurityList(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SecurityList()
        x.Init(buf, n + offset)
        return x


    # SecurityList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SecurityList
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # SecurityList
    def Securities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Security import Security
            obj = Security()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SecurityList
    def SecuritiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SecurityListStart(builder): builder.StartObject(2)
def SecurityListAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def SecurityListAddSecurities(builder, securities): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(securities), 0)
def SecurityListStartSecuritiesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SecurityListEnd(builder): return builder.EndObject()
